// <auto-generated />
using System;
using ClinicApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicApp.Migrations
{
    [DbContext(typeof(ClinicAppContext))]
    [Migration("20260909104818_edit_payment_table")]
    partial class edit_payment_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicApp.Audit.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("auditLogs");
                });

            modelBuilder.Entity("ClinicApp.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ClinicApp.Models.Appointment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PatientID")
                        .HasColumnType("int");

                    b.Property<int?>("ReceptID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<int?>("TherapistID")
                        .HasColumnType("int");

                    b.Property<decimal?>("feesOnMedicalService")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("feesOnpatient")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("medicalServiceID")
                        .HasColumnType("int");

                    b.Property<string>("modefiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("planID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PatientID");

                    b.HasIndex("ReceptID");

                    b.HasIndex("TherapistID");

                    b.HasIndex("medicalServiceID");

                    b.HasIndex("modefiedById");

                    b.HasIndex("planID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("ClinicApp.Models.Equipment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("modefiedById")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("CreatedById");

                    b.HasIndex("modefiedById");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("ClinicApp.Models.Exercise", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumberOfSets")
                        .HasColumnType("int");

                    b.Property<string>("VideoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("modefiedById")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CreatedById");

                    b.HasIndex("modefiedById");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("ClinicApp.Models.ExerciseCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("modefiedById")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("CreatedById");

                    b.HasIndex("modefiedById");

                    b.ToTable("ExerciseCategories");
                });

            modelBuilder.Entity("ClinicApp.Models.MedicalService", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("EndDateContract")
                        .HasColumnType("date");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDateContract")
                        .HasColumnType("date");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("modefiedById")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("CreatedById");

                    b.HasIndex("modefiedById");

                    b.ToTable("MedicalServices");
                });

            modelBuilder.Entity("ClinicApp.Models.Muscle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("modefiedById")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("CreatedById");

                    b.HasIndex("modefiedById");

                    b.ToTable("Muscles");
                });

            modelBuilder.Entity("ClinicApp.Models.Patient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyRelationShip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("datetime2");

                    b.Property<int>("LockCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RequirePasswordChange")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("isLocked")
                        .HasColumnType("bit");

                    b.Property<string>("modefiedById")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("CreatedById");

                    b.HasIndex("modefiedById");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ClinicApp.Models.Payment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AppointmentID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCredit")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MedicalServiceID")
                        .HasColumnType("int");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PatientID")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<int?>("ReceptID")
                        .HasColumnType("int");

                    b.Property<int?>("TherapistID")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("modefiedById")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("AppointmentID");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MedicalServiceID");

                    b.HasIndex("PatientID");

                    b.HasIndex("ReceptID");

                    b.HasIndex("TherapistID");

                    b.HasIndex("modefiedById");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ClinicApp.Models.Plan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("modefiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("numberOfSession")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CreatedById");

                    b.HasIndex("modefiedById");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("ClinicApp.Models.Receptionist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dayoff")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("datetime2");

                    b.Property<int>("LockCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedbyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequirePasswordChange")
                        .HasColumnType("bit");

                    b.Property<DateTime>("WorkTimeTO")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WorktimeFrom")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("isLocked")
                        .HasColumnType("bit");

                    b.Property<string>("modefiedById")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedbyId");

                    b.ToTable("Receptionists");
                });

            modelBuilder.Entity("ClinicApp.Models.Therapist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("datetime2");

                    b.Property<int>("LockCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManagerID")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedbyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequirePasswordChange")
                        .HasColumnType("bit");

                    b.Property<int>("SeniorityLevel")
                        .HasColumnType("int");

                    b.Property<int>("Specialization")
                        .HasColumnType("int");

                    b.Property<decimal>("hourRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("isLocked")
                        .HasColumnType("bit");

                    b.Property<string>("modefiedById")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("CreatedById");

                    b.HasIndex("ManagerID");

                    b.HasIndex("ModifiedbyId");

                    b.ToTable("Therapists");
                });

            modelBuilder.Entity("ClinicApp.Models.TherapySession", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AppointmentID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<int>("SessionStatus")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int?>("TheeapistID")
                        .HasColumnType("int");

                    b.Property<int?>("TreatmentPlanID")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("modefiedById")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("AppointmentID");

                    b.HasIndex("CreatedById");

                    b.HasIndex("TheeapistID");

                    b.HasIndex("TreatmentPlanID");

                    b.HasIndex("modefiedById");

                    b.ToTable("TherapySessions");
                });

            modelBuilder.Entity("ClinicApp.Models.TreatmentPlan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("modefiedById")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("CreatedById");

                    b.HasIndex("modefiedById");

                    b.ToTable("TreatmentPlans");
                });

            modelBuilder.Entity("ClinicApp.Models.TreatmentPlanExercises", b =>
                {
                    b.Property<int>("treatmentPlanID")
                        .HasColumnType("int");

                    b.Property<int>("exerciseID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Lastmodified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("modefiedById")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("treatmentPlanID", "exerciseID");

                    b.HasIndex("CreatedById");

                    b.HasIndex("exerciseID");

                    b.HasIndex("modefiedById");

                    b.ToTable("TreatmentPlanExercises");
                });

            modelBuilder.Entity("ExerciseEquipment", b =>
                {
                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseID")
                        .HasColumnType("int");

                    b.HasKey("EquipmentID", "ExerciseID");

                    b.HasIndex("ExerciseID");

                    b.ToTable("ExerciseEquipment");
                });

            modelBuilder.Entity("ExerciseMuscle", b =>
                {
                    b.Property<int>("ExerciseID")
                        .HasColumnType("int");

                    b.Property<int>("MuscleID")
                        .HasColumnType("int");

                    b.HasKey("ExerciseID", "MuscleID");

                    b.HasIndex("MuscleID");

                    b.ToTable("ExerciseMuscle");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClinicApp.Audit.AuditLog", b =>
                {
                    b.HasOne("ClinicApp.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicApp.Models.Appointment", b =>
                {
                    b.HasOne("ClinicApp.Data.ApplicationUser", "CreatedBY")
                        .WithMany("AppointmentsCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicApp.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientID");

                    b.HasOne("ClinicApp.Models.Receptionist", "Receptionist")
                        .WithMany("Appointments")
                        .HasForeignKey("ReceptID");

                    b.HasOne("ClinicApp.Models.Therapist", "Therapist")
                        .WithMany("Appointments")
                        .HasForeignKey("TherapistID");

                    b.HasOne("ClinicApp.Models.MedicalService", "MedicalService")
                        .WithMany("Appointments")
                        .HasForeignKey("medicalServiceID");

                    b.HasOne("ClinicApp.Data.ApplicationUser", "Modifiedby")
                        .WithMany("AppointmentsModified")
                        .HasForeignKey("modefiedById");

                    b.HasOne("ClinicApp.Models.Plan", "Plan")
                        .WithMany("Appointments")
                        .HasForeignKey("planID");

                    b.Navigation("CreatedBY");

                    b.Navigation("MedicalService");

                    b.Navigation("Modifiedby");

                    b.Navigation("Patient");

                    b.Navigation("Plan");

                    b.Navigation("Receptionist");

                    b.Navigation("Therapist");
                });

            modelBuilder.Entity("ClinicApp.Models.Equipment", b =>
                {
                    b.HasOne("ClinicApp.Data.ApplicationUser", "CreatedBY")
                        .WithMany("EquipmentCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicApp.Data.ApplicationUser", "Modifiedby")
                        .WithMany("EquipmentModified")
                        .HasForeignKey("modefiedById");

                    b.Navigation("CreatedBY");

                    b.Navigation("Modifiedby");
                });

            modelBuilder.Entity("ClinicApp.Models.Exercise", b =>
                {
                    b.HasOne("ClinicApp.Models.ExerciseCategory", "ExerciseCategory")
                        .WithMany("Exercises")
                        .HasForeignKey("CategoryID");

                    b.HasOne("ClinicApp.Data.ApplicationUser", "CreatedBY")
                        .WithMany("ExerciseCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicApp.Data.ApplicationUser", "Modifiedby")
                        .WithMany("ExerciseModified")
                        .HasForeignKey("modefiedById");

                    b.Navigation("CreatedBY");

                    b.Navigation("ExerciseCategory");

                    b.Navigation("Modifiedby");
                });

            modelBuilder.Entity("ClinicApp.Models.ExerciseCategory", b =>
                {
                    b.HasOne("ClinicApp.Data.ApplicationUser", "CreatedBY")
                        .WithMany("ExerciseCategoriesCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicApp.Data.ApplicationUser", "Modifiedby")
                        .WithMany("ExerciseCategoriesModified")
                        .HasForeignKey("modefiedById");

                    b.Navigation("CreatedBY");

                    b.Navigation("Modifiedby");
                });

            modelBuilder.Entity("ClinicApp.Models.MedicalService", b =>
                {
                    b.HasOne("ClinicApp.Data.ApplicationUser", "CreatedBY")
                        .WithMany("MedicalServiceCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicApp.Data.ApplicationUser", "Modifiedby")
                        .WithMany("MedicalServiceModified")
                        .HasForeignKey("modefiedById");

                    b.Navigation("CreatedBY");

                    b.Navigation("Modifiedby");
                });

            modelBuilder.Entity("ClinicApp.Models.Muscle", b =>
                {
                    b.HasOne("ClinicApp.Data.ApplicationUser", "CreatedBY")
                        .WithMany("MuscleCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicApp.Data.ApplicationUser", "Modifiedby")
                        .WithMany("MuscleModified")
                        .HasForeignKey("modefiedById");

                    b.Navigation("CreatedBY");

                    b.Navigation("Modifiedby");
                });

            modelBuilder.Entity("ClinicApp.Models.Patient", b =>
                {
                    b.HasOne("ClinicApp.Data.ApplicationUser", "appUser")
                        .WithOne("Patient")
                        .HasForeignKey("ClinicApp.Models.Patient", "AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicApp.Data.ApplicationUser", "CreatedBY")
                        .WithMany("PatientUserCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicApp.Data.ApplicationUser", "Modifiedby")
                        .WithMany("PatientUserModified")
                        .HasForeignKey("modefiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBY");

                    b.Navigation("Modifiedby");

                    b.Navigation("appUser");
                });

            modelBuilder.Entity("ClinicApp.Models.Payment", b =>
                {
                    b.HasOne("ClinicApp.Models.Appointment", "Appointment")
                        .WithMany("Payments")
                        .HasForeignKey("AppointmentID");

                    b.HasOne("ClinicApp.Data.ApplicationUser", "CreatedBY")
                        .WithMany("PaymentsCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicApp.Models.MedicalService", "MedicalService")
                        .WithMany("Payments")
                        .HasForeignKey("MedicalServiceID");

                    b.HasOne("ClinicApp.Models.Patient", "Patient")
                        .WithMany("payments")
                        .HasForeignKey("PatientID");

                    b.HasOne("ClinicApp.Models.Receptionist", "Receptionist")
                        .WithMany("Payments")
                        .HasForeignKey("ReceptID");

                    b.HasOne("ClinicApp.Models.Therapist", "Therapist")
                        .WithMany("Payments")
                        .HasForeignKey("TherapistID");

                    b.HasOne("ClinicApp.Data.ApplicationUser", "Modifiedby")
                        .WithMany("PaymentsModified")
                        .HasForeignKey("modefiedById");

                    b.Navigation("Appointment");

                    b.Navigation("CreatedBY");

                    b.Navigation("MedicalService");

                    b.Navigation("Modifiedby");

                    b.Navigation("Patient");

                    b.Navigation("Receptionist");

                    b.Navigation("Therapist");
                });

            modelBuilder.Entity("ClinicApp.Models.Plan", b =>
                {
                    b.HasOne("ClinicApp.Data.ApplicationUser", "CreatedBY")
                        .WithMany("PlanCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicApp.Data.ApplicationUser", "Modifiedby")
                        .WithMany("PlanModified")
                        .HasForeignKey("modefiedById");

                    b.Navigation("CreatedBY");

                    b.Navigation("Modifiedby");
                });

            modelBuilder.Entity("ClinicApp.Models.Receptionist", b =>
                {
                    b.HasOne("ClinicApp.Data.ApplicationUser", "appUser")
                        .WithOne("Receptionist")
                        .HasForeignKey("ClinicApp.Models.Receptionist", "AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicApp.Data.ApplicationUser", "CreatedBY")
                        .WithMany("ReceptionistUserCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicApp.Data.ApplicationUser", "Modifiedby")
                        .WithMany("ReceptionistUserModified")
                        .HasForeignKey("ModifiedbyId");

                    b.Navigation("CreatedBY");

                    b.Navigation("Modifiedby");

                    b.Navigation("appUser");
                });

            modelBuilder.Entity("ClinicApp.Models.Therapist", b =>
                {
                    b.HasOne("ClinicApp.Data.ApplicationUser", "appUser")
                        .WithOne("Therapist")
                        .HasForeignKey("ClinicApp.Models.Therapist", "AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicApp.Data.ApplicationUser", "CreatedBY")
                        .WithMany("TherapistUserCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicApp.Models.Therapist", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerID");

                    b.HasOne("ClinicApp.Data.ApplicationUser", "Modifiedby")
                        .WithMany("TherapistUserModified")
                        .HasForeignKey("ModifiedbyId");

                    b.Navigation("CreatedBY");

                    b.Navigation("Manager");

                    b.Navigation("Modifiedby");

                    b.Navigation("appUser");
                });

            modelBuilder.Entity("ClinicApp.Models.TherapySession", b =>
                {
                    b.HasOne("ClinicApp.Models.Appointment", "Appointment")
                        .WithMany("TherapySessions")
                        .HasForeignKey("AppointmentID");

                    b.HasOne("ClinicApp.Data.ApplicationUser", "CreatedBY")
                        .WithMany("TherapySessionCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicApp.Models.Therapist", "Therapist")
                        .WithMany("TherapySessions")
                        .HasForeignKey("TheeapistID");

                    b.HasOne("ClinicApp.Models.TreatmentPlan", "TreatmentPlan")
                        .WithMany("TherapySessions")
                        .HasForeignKey("TreatmentPlanID");

                    b.HasOne("ClinicApp.Data.ApplicationUser", "Modifiedby")
                        .WithMany("TherapySessionModified")
                        .HasForeignKey("modefiedById");

                    b.Navigation("Appointment");

                    b.Navigation("CreatedBY");

                    b.Navigation("Modifiedby");

                    b.Navigation("Therapist");

                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("ClinicApp.Models.TreatmentPlan", b =>
                {
                    b.HasOne("ClinicApp.Data.ApplicationUser", "CreatedBY")
                        .WithMany("TreatmentPlanCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicApp.Data.ApplicationUser", "Modifiedby")
                        .WithMany("TreatmentPlanModified")
                        .HasForeignKey("modefiedById");

                    b.Navigation("CreatedBY");

                    b.Navigation("Modifiedby");
                });

            modelBuilder.Entity("ClinicApp.Models.TreatmentPlanExercises", b =>
                {
                    b.HasOne("ClinicApp.Data.ApplicationUser", "CreatedBY")
                        .WithMany("TreatmentPlanExerciseCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicApp.Models.Exercise", "Exercise")
                        .WithMany("TreatmentPlanExercises")
                        .HasForeignKey("exerciseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicApp.Data.ApplicationUser", "Modifiedby")
                        .WithMany("TreatmentPlanExerciseModified")
                        .HasForeignKey("modefiedById");

                    b.HasOne("ClinicApp.Models.TreatmentPlan", "TreatmentPlan")
                        .WithMany("TreatmentPlanExercises")
                        .HasForeignKey("treatmentPlanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBY");

                    b.Navigation("Exercise");

                    b.Navigation("Modifiedby");

                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("ExerciseEquipment", b =>
                {
                    b.HasOne("ClinicApp.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicApp.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExerciseMuscle", b =>
                {
                    b.HasOne("ClinicApp.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicApp.Models.Muscle", null)
                        .WithMany()
                        .HasForeignKey("MuscleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClinicApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ClinicApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ClinicApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicApp.Data.ApplicationUser", b =>
                {
                    b.Navigation("AppointmentsCreated");

                    b.Navigation("AppointmentsModified");

                    b.Navigation("EquipmentCreated");

                    b.Navigation("EquipmentModified");

                    b.Navigation("ExerciseCategoriesCreated");

                    b.Navigation("ExerciseCategoriesModified");

                    b.Navigation("ExerciseCreated");

                    b.Navigation("ExerciseModified");

                    b.Navigation("MedicalServiceCreated");

                    b.Navigation("MedicalServiceModified");

                    b.Navigation("MuscleCreated");

                    b.Navigation("MuscleModified");

                    b.Navigation("Patient");

                    b.Navigation("PatientUserCreated");

                    b.Navigation("PatientUserModified");

                    b.Navigation("PaymentsCreated");

                    b.Navigation("PaymentsModified");

                    b.Navigation("PlanCreated");

                    b.Navigation("PlanModified");

                    b.Navigation("Receptionist");

                    b.Navigation("ReceptionistUserCreated");

                    b.Navigation("ReceptionistUserModified");

                    b.Navigation("Therapist");

                    b.Navigation("TherapistUserCreated");

                    b.Navigation("TherapistUserModified");

                    b.Navigation("TherapySessionCreated");

                    b.Navigation("TherapySessionModified");

                    b.Navigation("TreatmentPlanCreated");

                    b.Navigation("TreatmentPlanExerciseCreated");

                    b.Navigation("TreatmentPlanExerciseModified");

                    b.Navigation("TreatmentPlanModified");
                });

            modelBuilder.Entity("ClinicApp.Models.Appointment", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("TherapySessions");
                });

            modelBuilder.Entity("ClinicApp.Models.Exercise", b =>
                {
                    b.Navigation("TreatmentPlanExercises");
                });

            modelBuilder.Entity("ClinicApp.Models.ExerciseCategory", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("ClinicApp.Models.MedicalService", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ClinicApp.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("payments");
                });

            modelBuilder.Entity("ClinicApp.Models.Plan", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClinicApp.Models.Receptionist", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ClinicApp.Models.Therapist", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Payments");

                    b.Navigation("TherapySessions");
                });

            modelBuilder.Entity("ClinicApp.Models.TreatmentPlan", b =>
                {
                    b.Navigation("TherapySessions");

                    b.Navigation("TreatmentPlanExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
